#在application.properties文件中引入日志配置文件
#=====================================  log  =============================
logging:
  config: classpath:logback-boot.xml

##pageHelper分页
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
spring:
  main:
    allow-bean-definition-overriding: true

